#+TITLE: Cleaning Up

My wife and I have recently started looking for a permanent home. In doing so, we have also started to take inventory of our personal belongings and itemize what we want to move with us.

This has brought up a lot of happy, and some saddening memories.

We recently lost our beloved golden retriever, Riley, and this has weighed heavy on my heart for months. With Christmas around the corner, we are constantly reminded of his past life and how much happiness he brought us and others. We will always miss him, but we recognize that his memory is always with us and in those who shared his life and memories.

In celebration of the real-life memories I will always carry, I am also restarting my digital presence.

This personal site is a new start for me. I have decided to archive all of my previous articles and start fresh, writing about whatever is of interest to me, anything and everything.

I plan to work on some side-projects, some involving code and others involving music. I plan to explore new interests that I have never considered before such as argriculture, woodworking, and music theory.

This is a new chapter and one to be celebrated. I am excited and eager to begin. Welcome to a new beginning.
